Kay fortune binary search
gi
Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB (Somto)
$ git init
Reinitialized existing Git repository in C:/Users/Sum1/Desktop/IGHUB/.git/

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB (Somto)
$ ls
 Answers.txt
 binarysearch2.js
 binarysearch3.html
 conditionals.js
'CORRECTION DEVELOPERS GROUP 1 DESIGN ASSIGNMENT.docx'
'CORRECTION2 DEVELOPERS GROUP 1 DESIGN ASSIGNMENT.docx'
 Hello.js
'Html structure.html'
 htmlcuberotate.html.htm
'ighub notes.txt'
'IGHUBF2018 DEVELOPERS GROUP 1 MEMBERS.docx'
 index.html
 linearsearch.html
 newFellows/
'python game.py'
 Random.js
 split.js
 style.css.css
'sum of odd.js'

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB (Somto)
$ git add binarysearch3
fatal: Unable to create 'C:/Users/Sum1/Desktop/IGHUB/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB (Somto)
$ ls
 Answers.txt
 binarysearch2.js
 binarysearch3.html
 conditionals.js
'CORRECTION DEVELOPERS GROUP 1 DESIGN ASSIGNMENT.docx'
'CORRECTION2 DEVELOPERS GROUP 1 DESIGN ASSIGNMENT.docx'
 Hello.js
'Html structure.html'
 htmlcuberotate.html.htm
'ighub notes.txt'
'IGHUBF2018 DEVELOPERS GROUP 1 MEMBERS.docx'
 index.html
 linearsearch.html
 newFellows/
'python game.py'
 Random.js
 split.js
 style.css.css
'sum of odd.js'

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB (Somto)
$ mkdir binarysearch

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB (Somto)
$ ls
 Answers.txt
 binarysearch/
 binarysearch2.js
 binarysearch3.html
 conditionals.js
'CORRECTION DEVELOPERS GROUP 1 DESIGN ASSIGNMENT.docx'
'CORRECTION2 DEVELOPERS GROUP 1 DESIGN ASSIGNMENT.docx'
 Hello.js
'Html structure.html'
 htmlcuberotate.html.htm
'ighub notes.txt'
'IGHUBF2018 DEVELOPERS GROUP 1 MEMBERS.docx'
 index.html
 linearsearch.html
 newFellows/
'python game.py'
 Random.js
 split.js
 style.css.css
'sum of odd.js'

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB (Somto)
$ mv binarysearch3.html binarysearch

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB (Somto)
$ cd binarysearch

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (Somto)
$ ls
binarysearch3.html

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (Somto)
$ git branch binary
fatal: Not a valid object name: 'Somto'.

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (Somto)
$ git init
Initialized empty Git repository in C:/Users/Sum1/Desktop/IGHUB/binarysearch/.git/

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (master)
$ git branch binary
fatal: Not a valid object name: 'master'.

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (master)
$ git add
Nothing specified, nothing added.
Maybe you wanted to say 'git add .'?

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (master)
$ git add -a
error: unknown switch `a'
usage: git add [<options>] [--] <pathspec>...

    -n, --dry-run         dry run
    -v, --verbose         be verbose

    -i, --interactive     interactive picking
    -p, --patch           select hunks interactively
    -e, --edit            edit current diff and apply
    -f, --force           allow adding otherwise ignored files
    -u, --update          update tracked files
    --renormalize         renormalize EOL of tracked files (implies -u)
    -N, --intent-to-add   record only the fact that the path will be added later
    -A, --all             add changes from all tracked and untracked files
    --ignore-removal      ignore paths removed in the working tree (same as --no-all)
    --refresh             don't add, only refresh the index
    --ignore-errors       just skip files which cannot be added because of errors
    --ignore-missing      check if - even missing - files are ignored in dry run
    --chmod <(+/-)x>      override the executable bit of the listed files


Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (master)
$ git add .

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (master)
$ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

        new file:   binarysearch3.html


Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (master)
$ git branch

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (master)
$ git branch binary
fatal: Not a valid object name: 'master'.

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (master)
$ git branch somto
fatal: Not a valid object name: 'master'.

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (master)
$ git checkout -b somto
Switched to a new branch 'somto'

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (somto)
$ ls
binarysearch3.html

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (somto)
$ git add .

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (somto)
$ git commit -m "Ihave successfully done the binary search javascript project"
[somto (root-commit) f569402] Ihave successfully done the binary search javascript project
 1 file changed, 34 insertions(+)
 create mode 100644 binarysearch3.html

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (somto)
$ git log
commit f5694027ba6d01cf2672ce2a0a5cc3322fd8eae4 (HEAD -> somto)
Author: Somto Mbanefo <somto.mbanefo@gmail.com>
Date:   Wed Oct 3 16:57:00 2018 +0100

    Ihave successfully done the binary search javascript project

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (somto)
$ git log --oneline
f569402 (HEAD -> somto) Ihave successfully done the binary search javascript project

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (somto)
$ git status
On branch somto
nothing to commit, working tree clean

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (somto)
$ git push https://github.com/segunemma2003/ighub.git somto
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
Username for 'https://github.com': somtom1
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 689 bytes | 229.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote:
remote: Create a pull request for 'somto' on GitHub by visiting:
remote:      https://github.com/segunemma2003/ighub/pull/new/somto
remote:
To https://github.com/segunemma2003/ighub.git
 * [new branch]      somto -> somto

Sum1@Som1s-PC MINGW64 ~/Desktop/IGHUB/binarysearch (somto)
$ git status
On branch somto
nothing to commit, working tree clean